# .air.toml for Gix
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/gix-server ./cmd/gix-server"
bin = "./tmp/gix-server"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true