# k8s/04-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gix-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gix-backend
  template:
    metadata:
      labels:
        app: gix-backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gix-backend
          image: niutaq/gix-backend:v1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
              ephemeral-storage: 128Mi
            limits:
              memory: 512Mi
              ephemeral-storage: 1Gi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gix-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: gix-config
                  key: REDIS_URL
            - name: SWAGGER_HOST
              value: "165.227.246.100:8080"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: gix-backend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: drpc
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: gix-backend
