apiVersion: v1
kind: Service
metadata:
  name: {{ include "gix.fullname" . }}-service
  labels:
    {{- include "gix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- else if and (eq .Values.service.type "LoadBalancer") .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    - name: drpc
      port: {{ .Values.service.ports.drpc }}
      targetPort: {{ .Values.service.ports.drpc }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.drpc }}
      nodePort: {{ .Values.service.nodePorts.drpc }}
      {{- else if and (eq .Values.service.type "LoadBalancer") .Values.service.nodePorts.drpc }}
      nodePort: {{ .Values.service.nodePorts.drpc }}
      {{- end }}
  selector:
    {{- include "gix.selectorLabels" . | nindent 4 }}
